[package]
name = "pumpkin-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
colored = "2"
md5 = "0.7.0"

num-traits = "0.2.19"
num-derive = { version = "0.4.2" }
